In [1]:
import pandas as pd

In [104]:
df = pd.read_csv('startup.txt', sep=',')

In [105]:
df.head()

Startup Description  Unique Idea  \
0  Revolutionary AI-powered healthcare platform            1   
1       Unique e-commerce for handmade artisans            0   
2       Cutting-edge renewable energy solutions            1   
3        Innovative food delivery and meal kits            0   
4      Pioneering virtual reality gaming studio            1   

   Highly Success Possibility  Great Future  
0                           1             1  
1                           1             1  
2                           0             1  
3                           0             0  
4                           1             1

In [106]:
df.tail()

Startup Description  Unique Idea  \
115           Advanced water-saving irrigation systems            1   
116          Virtual reality therapy for mental health            1   
117   Smart city infrastructure for sustainable living            1   
118             Next-gen electric bike rental services            1   
119  Precision medicine research for personalized t...            1   

     Highly Success Possibility  Great Future  
115                           1             1  
116                           0             0  
117                           1             1  
118                           1             1  
119                           0             0

In [107]:
print(df['Startup Description'])

0           Revolutionary AI-powered healthcare platform
1                Unique e-commerce for handmade artisans
2                Cutting-edge renewable energy solutions
3                 Innovative food delivery and meal kits
4               Pioneering virtual reality gaming studio
                             ...                        
115             Advanced water-saving irrigation systems
116            Virtual reality therapy for mental health
117     Smart city infrastructure for sustainable living
118               Next-gen electric bike rental services
119    Precision medicine research for personalized t...
Name: Startup Description, Length: 120, dtype: object


In [108]:
df.shape

(120, 4)

In [109]:
df.dtypes

Startup Description           object
Unique Idea                    int64
Highly Success Possibility     int64
Great Future                   int64
dtype: object

In [110]:
X = df['Startup Description']
y = df[df.columns[1:]].values

In [111]:
print(X)

0           Revolutionary AI-powered healthcare platform
1                Unique e-commerce for handmade artisans
2                Cutting-edge renewable energy solutions
3                 Innovative food delivery and meal kits
4               Pioneering virtual reality gaming studio
                             ...                        
115             Advanced water-saving irrigation systems
116            Virtual reality therapy for mental health
117     Smart city infrastructure for sustainable living
118               Next-gen electric bike rental services
119    Precision medicine research for personalized t...
Name: Startup Description, Length: 120, dtype: object


In [112]:
print(y)

[[1 1 1]
 [0 1 1]
 [1 0 1]
 [0 0 0]
 [1 1 1]
 [0 0 0]
 [1 1 1]
 [1 1 0]
 [1 0 0]
 [1 1 1]
 [1 0 0]
 [1 1 1]
 [0 1 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]
 [1 0 0]
 [1 1 1]
 [1 0 0]
 [1 1 1]
 [1 0 0]
 [1 1 1]
 [0 0 0]
 [1 1 1]
 [1 1 1]
 [0 1 1]
 [1 1 1]
 [1 0 0]
 [1 1 1]
 [1 0 0]
 [1 1 1]
 [1 0 0]
 [1 1 1]
 [1 0 0]
 [1 1 1]
 [1 0 0]
 [1 0 0]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 0 0]
 [1 1 1]
 [1 0 0]
 [1 0 0]
 [1 1 1]
 [1 1 1]
 [1 0 0]
 [1 0 0]
 [1 1 1]
 [1 1 1]
 [0 0 0]
 [1 1 1]
 [1 0 0]
 [1 1 1]
 [0 0 0]
 [1 1 1]
 [1 0 0]
 [1 1 1]
 [0 0 0]
 [1 1 1]
 [1 0 0]
 [1 1 1]
 [1 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]
 [0 0 0]
 [1 1 1]
 [1 0 0]
 [1 1 1]
 [1 0 0]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [0 1 1]
 [1 1 1]
 [1 0 0]
 [1 1 1]
 [1 1 1]
 [0 0 0]
 [1 1 1]
 [1 0 0]
 [1 1 1]
 [1 1 1]
 [1 0 0]
 [1 1 1]
 [0 1 1]
 [1 1 1]
 [1 0 0]
 [1 1 1]
 [1 0 0]
 [1 1 1]
 [0 1 1]
 [1 1 1]
 [1 0 0]
 [1 1 1]
 [1 0 0]
 [1 1 1]
 [1 1 1]
 [1 0 0]
 [1 1 1]
 [1 0 0]
 [1 1 1]
 [1 1 1]
 [1 0 0]
 [0 1 1]
 [1 1 1]
 [1 0 0]
 [1 1 1]
 [1 1 1]
 

In [113]:
from tensorflow.keras.layers import TextVectorization

In [114]:
MAX_FEATURES = 200000 # number of words in the vocab

In [115]:
vectorizer = TextVectorization(max_tokens=MAX_FEATURES,
                               output_sequence_length=1800,
                               output_mode='int')

In [116]:
vectorizer.adapt(X.values)

In [117]:
import tensorflow as tf

In [118]:
vectorized_text = vectorizer(X.values)

print(vectorized_text)

tf.Tensor(
[[ 76  40  11 ...   0   0   0]
 [122  96   2 ...   0   0   0]
 [ 60  30   8 ...   0   0   0]
 ...
 [ 24 102  87 ...   0   0   0]
 [ 25  28 105 ...   0   0   0]
 [ 49  83  48 ...   0   0   0]], shape=(120, 1800), dtype=int64)


In [119]:
vectorized_text.shape

TensorShape([120, 1800])

In [120]:
# Assigning the vectorized text to X again
X = vectorized_text

In [121]:
# Checking by printing a line
X[10]

<tf.Tensor: shape=(1800,), dtype=int64, numpy=array([ 12, 136, 173, ...,   0,   0,   0], dtype=int64)>

In [122]:
# Building a LSTM  model

In [123]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dropout, Bidirectional, Dense, Embedding

In [140]:
model = Sequential()
# Create the embedding layer 
model.add(Embedding(MAX_FEATURES+1, 16))
# Bidirectional LSTM Layer
model.add(Bidirectional(LSTM(16, activation='tanh')))
# Feature extractor Fully connected layers
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))

# Final layer 
model.add(Dense(3, activation='softmax'))

In [141]:
model.compile(loss='BinaryCrossentropy', optimizer='Adam', metrics=["accuracy"])

In [142]:
model.summary()

Model: "sequential_24"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_24 (Embedding)    (None, None, 16)          3200016   
                                                                 
 bidirectional_25 (Bidirecti  (None, 32)               4224      
 onal)                                                           
                                                                 
 dense_61 (Dense)            (None, 128)               4224      
                                                                 
 dropout_16 (Dropout)        (None, 128)               0         
                                                                 
 dense_62 (Dense)            (None, 3)                 387       
                                                                 
Total params: 3,208,851
Trainable params: 3,208,851
Non-trainable params: 0
___________________________________________

In [143]:
history = model.fit(X,y, epochs=5)

Epoch 1/5
4/4 [==============================] - 13s 1s/step - loss: 0.6918 - accuracy: 0.4667
Epoch 2/5
4/4 [==============================] - 6s 1s/step - loss: 0.6862 - accuracy: 0.7917
Epoch 3/5
4/4 [==============================] - 5s 1s/step - loss: 0.6804 - accuracy: 0.8333
Epoch 4/5
4/4 [==============================] - 6s 1s/step - loss: 0.6705 - accuracy: 0.8167
Epoch 5/5
4/4 [==============================] - 6s 1s/step - loss: 0.6613 - accuracy: 0.8750


In [144]:
# Testing with the real data

In [150]:
input_text = vectorizer('Al based Startup Validation and System')

In [151]:
import numpy as np

In [152]:
res = model.predict(np.expand_dims(input_text,0))

1/1 [==============================] - 0s 160ms/step


In [149]:
print(res)

[[0.3679812  0.33204198 0.2999769 ]]


In [155]:
df = pd.read_csv('test.txt', sep=',')

In [156]:
X_test = df['Startup Description']
y_test = df[df.columns[1:]].values

In [157]:
X_test = vectorizer(X_test.values)

In [160]:
res = model.predict(X_test)

1/1 [==============================] - 0s 234ms/step


[[1 0 0]
 [1 1 1]
 [1 0 0]
 [1 0 0]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 0 0]
 [1 1 1]
 [1 0 0]
 [1 0 0]
 [1 1 1]
 [1 1 1]
 [1 0 0]
 [1 0 0]
 [1 1 1]]
